### ISSUE TITLE
Windows cli (cli-win.exe) unexpectedly shut itself down.

### ISSUE THREAD

**Issue by kornkaobat** [Richienb/rosav#11]
**Describe the bug**
Windows cli (cli-win.exe) unexpectedly shut itself down after trying to update hash list. After that I couldn't enter the program again even if I redownloaded the whole .exe.

**To Reproduce**
1. Start the program without admin previlege (cli-win.exe) using the latest version avaliable.
2. Wait and it should shut itself down.

**Expected behavior**
Normal function would be a spike in internet traffic noticeable in Resource Monitor.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Version 1809 (x64)
 - Browser Chrome
 - Version 74.0.3729.131

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by kornkaobat** [comment]
Oh I start the program directly, that might be incorrect use case.

**Comment by Richienb** [comment]
If you want to launch the CLI via the file, you need to run it via cmd (on similar) like this:

![CMD Example](https://user-images.githubusercontent.com/29491356/57497519-1e8fb300-732c-11e9-85c2-1acc4a760068.PNG)

**Comment by kornkaobat** [comment]
Thank you. Problem solved.
