### ISSUE TITLE
Scan time could potentially take too long.

### ISSUE THREAD

**Issue by kornkaobat** [Richienb/rosav#2]
Using MD5 to compare hashes between malware samples and users' files could potentially take too long as the number of hash is about _33 million_ and the average number of file on a Harddisk is about _30,000 files_. 
Leading from my initial testing, it took my script (which works the same as this project but in a different programming language) about 15 seconds _@50% 7th Gen i5-7200U CPU running at max clock speed_. That leads to this mathematical equation of scan time.

S=15*f (seconds)
  =15x30000
  =**450,000 seconds/ 5 days scan time**

which doesn't include the MD5 hashing process due to HDD and SSD speed difference.
It could potentially be a _second-opinion CLI scanner_ but, newer hash functions or newer ways to deal with this problem should've been found first.

A nice start could be scanning using only the latest 1,000,000 hashes avaliable and call it a _recent malware mode_.

**Comment by Richienb** [comment]
Thanks for your input. A `recent malware mode` has been added to the TODO list in https://github.com/Richienb/rosav/commit/27250c07a9c2e0472a6b3adcc98b11ef8e0a470e.

**Comment by kornkaobat** [comment]
@Richienb No need for recent malware mode. Your engine works really fast (65k infected files removed in 40 minutes).
